# Default library values
nameOverride: ''
fullnameOverride: ''

#
# Secrets to create
#
secrets:
  - name: 'apiKey'
    value: ''

#
# Application Config
#
application:
  config:
    # Filename of configuration
    filename: 'config.xml'
    # Configuration file contents
    contents: |
      <Config>
          <LogLevel>info</LogLevel>
          <EnableSsl>False</EnableSsl>
          <Port>8787</Port>
          <UrlBase>readarr</UrlBase>
          <BindAddress>*</BindAddress>
          <ApiKey>$apiKey</ApiKey>
          <AnalyticsEnabled>False</AnalyticsEnabled>
          <AuthenticationMethod>External</AuthenticationMethod>
          <UpdateMechanism>Docker</UpdateMechanism>
          <Branch>develop</Branch>
          <InstanceName>Readarr</InstanceName>
        </Config>
    # Secrets to inject - if any - to the config. In the config they must be defined as $secret
    secrets: [ 'apiKey' ]
    # Path the file will be mounted to in the config
    mountPath: '/config/config.xml'

#
# Resource - DEPLOYMENT
# This is to set up and define the application deployment
#
deployment:
  container:
    image:
      repository: 'lscr.io/linuxserver/readarr'

    env:
      - name: 'PGID'
        value: '1000'
      - name: 'PUID'
        value: '1000'

    ports:
      - name: 'http'
        containerPort: 8787
        protocol: 'TCP'

    # Additional volumeMounts on the output Deployment definition.
    volumeMounts:
      - name: 'config'
        mountPath: '/config'
      - name: 'downloads'
        mountPath: '/downloads'
      - name: 'ebooks'
        mountPath: '/ebooks'

  volumes:
    config:
      persistentVolumeClaim:
        claimName: 'readarr-config'
    downloads:
      emptyDir: {}
    ebooks:
      emptyDir: {}

persistentVolumeClaims:
  readarr-config:
    accessMode: 'ReadWriteOnce'
    requestStorage: '1Gi'
    selector: {}

service:
  type: 'ClusterIP'
  ports:
    - port: 8787
      targetPort: 'http'
      protocol: 'TCP'
      name: 'http'

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: 'media-servarr.local'
      paths:
        - path: '/readarr'
          pathType: 'Prefix'
          port: 8787
  tls: []
