apiVersion: 'v2'
name: 'radarr'
description: 'Chart for Radarr'
type: 'application'
version: 0.1.0
appVersion: 'v5.3.2.8504'
dependencies:
  - name: 'media-servarr-base'
    version: 0.1.0
    repository: "file://../.."
