---
# Source: radarr/templates/application.yaml
apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'radarr'
  labels:
    helm.sh/chart: radarr-0.1.0
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/version: "v5.3.2.8504"
    app.kubernetes.io/managed-by: Helm
spec:
  
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
      app.kubernetes.io/instance: radarr
  template:
    metadata:
      labels:
        helm.sh/chart: radarr-0.1.0
        app.kubernetes.io/name: radarr
        app.kubernetes.io/instance: radarr
        app.kubernetes.io/version: "v5.3.2.8504"
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: 'radarr'
          image: 'lscr.io/linuxserver/radarr:5.2.6.8376-ls200'
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 7575
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: downloads
            - mountPath: /film
              name: film
      volumes:
        - name: config
          nfs:
            path: /srv/storage/services/radarr
            server: lovelace
        - name: downloads
          nfs:
            path: /srv/downloads
            server: lovelace
        - name: film
          nfs:
            path: /srv/media/film
            server: lovelace
