# Default library values
nameOverride: ''
fullnameOverride: ''

#
# Secrets to create
#
secrets:
  - name: 'apiKey'
    value: '' # Leaving blank will auto generate

#
# Application Config
#
application:
  config:
    # Filename of configuration
    filename: 'config.xml'
    # Configuration file contents
    contents: |
      <Config>
          <LogLevel>info</LogLevel>
          <EnableSsl>False</EnableSsl>
          <Port>7878</Port>
          <UrlBase>radarr</UrlBase>
          <BindAddress>*</BindAddress>
          <ApiKey>$apiKey</ApiKey>
          <AnalyticsEnabled>False</AnalyticsEnabled>
          <AuthenticationMethod>External</AuthenticationMethod>
          <UpdateMechanism>Docker</UpdateMechanism>
          <Branch>main</Branch>
          <InstanceName>Radarr</InstanceName>
        </Config>
    # Secrets to inject - if any - to the config. In the config they must be defined as $secret
    secrets: [ 'apiKey' ]
    # Path the file will be mounted to in the config
    mountPath: '/config/config.xml'

#
# Resource - DEPLOYMENT
# This is to set up and define the application deployment
#
deployment:
  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  container:
    image:
      repository: 'lscr.io/linuxserver/radarr'
      pullPolicy: 'IfNotPresent'

    env:
      - name: 'PGID'
        value: '1000'
      - name: 'PUID'
        value: '1000'

    ports:
      - name: 'http'
        containerPort: 7878
        protocol: 'TCP'

    livenessProbe:
      httpGet:
        path: '/'
        port: 'http'
    readinessProbe:
      httpGet:
        path: '/'
        port: 'http'

    # Additional volumeMounts on the output Deployment definition.
    volumeMounts:
      - name: 'config'
        mountPath: '/config'
      - name: 'downloads'
        mountPath: '/downloads'
      - name: 'film'
        mountPath: '/film'

  volumes:
    - name: 'config'
      nfs:
       server: 'lovelace'
       path: '/srv/storage/services/radarr'
    - name: 'downloads'
      nfs:
       server: 'lovelace'
       path: '/srv/downloads'
    - name: 'film'
      nfs:
       server: 'lovelace'
       path: '/srv/media/film'

service:
  type: 'ClusterIP'
  ports:
    - port: 7878
      targetPort: 'http'
      protocol: 'TCP'
      name: 'http'

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: 'media-servarr.local'
      paths:
        - path: '/radarr/'
          pathType: 'Prefix'
          port: 7878
  tls: []

