{{- define "media-servarr-base.serviceaccount" -}}
{{- if .Values.serviceAccount -}}
{{- if .Values.serviceAccount.create -}}
---

apiVersion: 'v1'
kind: 'ServiceAccount'
metadata:
  name: {{ include "media-servarr-base.serviceAccount.name" . }}
  labels:
    {{- include "media-servarr-base.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- end }}
{{- end }}
