name: 'Lint Helm'

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'

    # Set up Helm
    - name: 'Set up Helm'
      uses: 'azure/setup-helm@v3.5'

    - name: 'Update dependencies'
      run: |
        #!/bin/bash

        for chart in ./charts/*; do
          cd $chart
          helm dependency update
          cd -
        done;

    # Lint Helm charts
    - name: 'Lint Helm charts'
      run: 'make lint'
